title: how-are-you
hero_image: images/introduction.png
description: how-are-you description
version: 4
listed: false
copyedit: false
last_tested: "2020-05-11"
steps:
  - title: Introduction
  - title: Translate your message
  - title: Challenge: Receive a message back
  - title: "What's next"
