title: How are you?
hero_image: images/introduction.png
description: Ask someone how they are in their own language and translate their message back to you
version: 4
listed: false
copyedit: false
last_tested: "2020-05-11"
steps:
  - title: Introduction
  - title: Translate your message
  - title: Challenge: Receive a message back
    challenge: true  
  - title: What's next

