---
title: How are you?
hero_image: images/introduction.png
description: Ask someone how they are in a different language and translate their
  message back to you
version: 4
listed: true
copyedit: true
last_tested: '2020-09-01'
steps:
- title: Introduction
- title: Translate your message
  completion:
  - engaged
- title: 'Challenge: phrase book'
  challenge: true
  completion:
  - internal
- title: What next?
  completion:
  - external
